on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: pipx install poetry
        name: Install poetry
      - run: pipx install dunamai
