on:
  push:
    tags:
      - "v*"
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: pipx install poetry
      - run: pipx install dunamai
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11.0
          cache: "poetry"

      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        name: Login to PyPI

      - run: poetry version $(dunamai from git --style pep440)
      - run: poetry build
      - run: poetry publish
        if: ${{ startsWith(github.ref, "/refs/tags") }}
